#################################################################
# Example render.yaml                                           #
# Do not use this file directly! Consult it for reference only. #
#################################################################

# List all services *except* PostgreSQL databases here
services:
  # A web service on the Ruby native runtime
  - type: web
    runtime: node
    name: sm-esports-web
    repo: https://github.com/aniv-sm-esports/sm-esports-web # Default: Repo containing render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1 for new services
    region: oregon    # Default: oregon
    plan: free        # Default: starter
    branch: main      # Default: master
    startCommand: npm start
    autoDeploy: true  # Disable automatic deploys
